"""add streak and health tracking fields

Revision ID: add29834da46
Revises: 0004_name_emergency
Create Date: 2026-05-16 23:05:46.978449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add29834da46'
down_revision: Union[str, None] = '0004_name_emergency'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_patients_patient_id'), table_name='doctor_patients')
    op.drop_constraint(op.f('health_records_user_id_key'), 'health_records', type_='unique')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=True)
    op.add_column('user_profiles', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_profiles', sa.Column('last_checkin_date', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_health_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user_profiles', 'id',
               existing_type=sa.UUID(),
               comment='Mirrors users.id',
               existing_comment='Mirrors auth.users.id from Supabase',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('user_profiles', 'id',
               existing_type=sa.UUID(),
               comment='Mirrors auth.users.id from Supabase',
               existing_comment='Mirrors users.id',
               existing_nullable=False)
    op.drop_column('user_profiles', 'last_health_update')
    op.drop_column('user_profiles', 'last_checkin_date')
    op.drop_column('user_profiles', 'longest_streak')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('health_records_user_id_key'), 'health_records', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_doctor_patients_patient_id'), 'doctor_patients', ['patient_id'], unique=False)
    # ### end Alembic commands ###
