"""add SMS reminder fields to user profiles

Revision ID: c8dac45692b1
Revises: 0006_health_80
Create Date: 2026-05-17 05:30:09.361755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8dac45692b1'
down_revision: Union[str, None] = '0006_health_80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop child tables first to avoid FK constraint violations
    op.drop_index(op.f('idx_health_document_chunks_document_id'), table_name='health_document_chunks')
    op.drop_index(op.f('idx_health_document_chunks_user_id'), table_name='health_document_chunks')
    op.drop_table('health_document_chunks')
    op.drop_index(op.f('idx_health_documents_uploaded_at'), table_name='health_documents')
    op.drop_index(op.f('idx_health_documents_user_id'), table_name='health_documents')
    op.drop_table('health_documents')
    # Drop tables in correct dependency order (children first)
    # 1. checkin_answers depends on checkin_voice_notes
    op.drop_index(op.f('idx_checkin_answers_q_id'), table_name='checkin_answers')
    op.drop_index(op.f('idx_checkin_answers_session_id'), table_name='checkin_answers')
    op.drop_index(op.f('idx_checkin_answers_user_id'), table_name='checkin_answers')
    op.drop_table('checkin_answers')
    # 2. checkin_voice_notes depends on rppg_results
    op.drop_index(op.f('idx_voice_notes_chest_pain'), table_name='checkin_voice_notes', postgresql_where='(symptom_chest_pain = true)')
    op.drop_index(op.f('idx_voice_notes_created_at'), table_name='checkin_voice_notes')
    op.drop_index(op.f('idx_voice_notes_session_id'), table_name='checkin_voice_notes')
    op.drop_index(op.f('idx_voice_notes_urgent'), table_name='checkin_voice_notes', postgresql_where='(requires_urgent_notice = true)')
    op.drop_index(op.f('idx_voice_notes_user_id'), table_name='checkin_voice_notes')
    op.drop_table('checkin_voice_notes')
    # 3. rppg_results (no dependencies)
    op.drop_index(op.f('idx_rppg_results_created_at'), table_name='rppg_results')
    op.drop_index(op.f('idx_rppg_results_pulse_cat'), table_name='rppg_results')
    op.drop_index(op.f('idx_rppg_results_session_id'), table_name='rppg_results')
    op.drop_index(op.f('idx_rppg_results_user_id'), table_name='rppg_results')
    op.drop_table('rppg_results')
    op.drop_index(op.f('idx_user_knowledge_chunks_created_at'), table_name='user_knowledge_chunks')
    op.drop_index(op.f('idx_user_knowledge_chunks_source_type'), table_name='user_knowledge_chunks')
    op.drop_index(op.f('idx_user_knowledge_chunks_user_id'), table_name='user_knowledge_chunks')
    op.drop_table('user_knowledge_chunks')
    op.drop_column('checkup_sessions', 'signal_quality')
    op.drop_column('checkup_sessions', 'voice_checkin')
    op.drop_column('checkup_sessions', 'completed_reason')
    op.drop_column('checkup_sessions', 'estimated_pulse_bpm')
    op.drop_column('checkup_sessions', 'rppg_data')
    op.drop_column('checkup_sessions', 'session_notes_for_user')
    op.drop_column('checkup_sessions', 'pulse_category')
    op.drop_column('checkup_sessions', 'duration_seconds')
    op.drop_column('checkup_sessions', 'user_context_used')
    op.drop_index(op.f('ix_doctor_patients_initiator'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_status'), table_name='doctor_patients')
    op.drop_index(op.f('ix_message_threads_status'), table_name='message_threads')
    # Add SMS reminder fields with server defaults for existing rows
    op.add_column('user_profiles', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='America/Los_Angeles'))
    op.add_column('user_profiles', sa.Column('sms_reminders_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_profiles', sa.Column('last_reminder_sent_date', sa.Date(), nullable=True))

    # Remove server defaults after backfilling (defaults now handled in Python code)
    op.alter_column('user_profiles', 'timezone', server_default=None)
    op.alter_column('user_profiles', 'sms_reminders_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_reminder_sent_date')
    op.drop_column('user_profiles', 'sms_reminders_enabled')
    op.drop_column('user_profiles', 'timezone')
    op.create_index(op.f('ix_message_threads_status'), 'message_threads', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_patients_status'), 'doctor_patients', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_patients_initiator'), 'doctor_patients', ['initiator_id'], unique=False)
    op.add_column('checkup_sessions', sa.Column('user_context_used', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('pulse_category', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('session_notes_for_user', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('rppg_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('estimated_pulse_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('completed_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('voice_checkin', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checkup_sessions', sa.Column('signal_quality', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('user_knowledge_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_knowledge_chunks_pkey'))
    )
    op.create_index(op.f('idx_user_knowledge_chunks_user_id'), 'user_knowledge_chunks', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_knowledge_chunks_source_type'), 'user_knowledge_chunks', ['user_id', 'source_type'], unique=False)
    op.create_index(op.f('idx_user_knowledge_chunks_created_at'), 'user_knowledge_chunks', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('checkin_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('raw_transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cleaned_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_voice_notes.session_id'], name=op.f('checkin_answers_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checkin_answers_pkey'))
    )
    op.create_index(op.f('idx_checkin_answers_user_id'), 'checkin_answers', ['user_id'], unique=False)
    op.create_index(op.f('idx_checkin_answers_session_id'), 'checkin_answers', ['session_id'], unique=False)
    op.create_index(op.f('idx_checkin_answers_q_id'), 'checkin_answers', ['question_id'], unique=False)
    op.create_table('rppg_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completed_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_pipeline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_mode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_pulse_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pulse_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pulse_label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retake_recommended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('retake_reasons', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('pos_hr_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chrom_hr_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('green_hr_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('consensus_hr_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hr_trend', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mean_window_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_window_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_window_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('range_window_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('std_window_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('window_values_bpm', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('window_size_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pos_chrom_diff_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pos_green_diff_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chrom_green_diff_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agreement_quality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outlier_methods', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('signal_quality_overall', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('method_agreement_quality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hr_stability', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waveform_strength', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('snr_like_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dominant_frequency_hz', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dominant_frequency_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waveform_sample_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_window_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('face_detected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('multiple_faces_detected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recording_duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_fps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frame_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wellness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wellness_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_next_step', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rppg_results_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('rppg_results_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_rppg_results_user_id'), 'rppg_results', ['user_id'], unique=False)
    op.create_index(op.f('idx_rppg_results_session_id'), 'rppg_results', ['session_id'], unique=False)
    op.create_index(op.f('idx_rppg_results_pulse_cat'), 'rppg_results', ['pulse_category'], unique=False)
    op.create_index(op.f('idx_rppg_results_created_at'), 'rppg_results', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('checkin_voice_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('cleaned_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('care_team_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_next_step', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('possible_context', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('requires_urgent_notice', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('urgent_notice_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('symptom_chest_pain', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_shortness_of_breath', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_dizziness', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_severe_headache', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_vision_changes', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_heavy_bleeding', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_reduced_fetal_movement', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_fever_or_chills', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symptom_mood_concern', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ai_cleanup_skipped', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ai_cleanup_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rppg_result_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rppg_result_id'], ['rppg_results.id'], name=op.f('checkin_voice_notes_rppg_result_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('checkin_voice_notes_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('checkin_voice_notes_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_voice_notes_user_id'), 'checkin_voice_notes', ['user_id'], unique=False)
    op.create_index(op.f('idx_voice_notes_urgent'), 'checkin_voice_notes', ['requires_urgent_notice'], unique=False, postgresql_where='(requires_urgent_notice = true)')
    op.create_index(op.f('idx_voice_notes_session_id'), 'checkin_voice_notes', ['session_id'], unique=False)
    op.create_index(op.f('idx_voice_notes_created_at'), 'checkin_voice_notes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_voice_notes_chest_pain'), 'checkin_voice_notes', ['symptom_chest_pain'], unique=False, postgresql_where='(symptom_chest_pain = true)')
    op.create_table('health_document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['health_documents.id'], name=op.f('health_document_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('health_document_chunks_pkey'))
    )
    op.create_index(op.f('idx_health_document_chunks_user_id'), 'health_document_chunks', ['user_id'], unique=False)
    op.create_index(op.f('idx_health_document_chunks_document_id'), 'health_document_chunks', ['document_id'], unique=False)
    op.create_table('health_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.TEXT(), server_default=sa.text("'application/pdf'::text"), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('processing_status', sa.TEXT(), server_default=sa.text("'uploaded'::text"), autoincrement=False, nullable=False),
    sa.Column('extracted_text_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('health_documents_pkey'))
    )
    op.create_index(op.f('idx_health_documents_user_id'), 'health_documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_health_documents_uploaded_at'), 'health_documents', [sa.literal_column('uploaded_at DESC')], unique=False)
    # ### end Alembic commands ###
