"""add phone_number to user_profiles

Revision ID: d3af7b4be86f
Revises: add29834da46
Create Date: 2026-05-17 02:15:47.496398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd3af7b4be86f'
down_revision: Union[str, None] = 'add29834da46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'phone_number')
    # ### end Alembic commands ###
